name: Lints and Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v1
      - name: Node.js setup
        uses: actions/setup-node@1.1.0
      - name: Instalation of dependencies
        run: npm ci
      - name: Lint
        run: npm run Lint
      - name: Build and Prod
        run: npm run build

